### ISSUE TITLE
Upgrade to tslint 4

### ISSUE THREAD

**Issue by schickling** [blakeembrey/tslint-config-standard#13]
Tslint 4 introduced a few breaking changes: https://github.com/palantir/tslint/releases/tag/4.0.0

It would be nice if this package would reflect the same changes in a new version.

**Comment by unindented** [comment]
Yes please!

**Comment by blakeembrey** [comment]
I think there's already a PR: https://github.com/blakeembrey/tslint-config-standard/pull/12.

**Comment by blakeembrey** [comment]
Fixed in https://github.com/blakeembrey/tslint-config-standard/releases/tag/v2.0.0.
