### ISSUE TITLE
use ter-indent for better indentation rules

### ISSUE THREAD

**Issue by jmlopez-rod** [blakeembrey/tslint-config-standard#15]
Just noticed the configuration points to the one provided by tslint. If you have some rules about indentation you can try the one in the tslint-eslint-rules project: https://github.com/buzinas/tslint-eslint-rules/blob/master/src/docs/rules/terIndentRule.md

It is a port of the one from eslint so I would look at their docs to see the examples of usage.

**Comment by blakeembrey** [comment]
Thanks for the notice, I've adopted it now.

**Comment by unional** [comment]
Just notice there is an issue related to this:
https://github.com/palantir/tslint/issues/3027

**Comment by jmlopez-rod** [comment]
Woah, that's bad... `ter-indent` is from https://github.com/buzinas/tslint-eslint-rules what versions of tslint and tslint-eslint-rules are  you using?

**Comment by rohmanhm** [comment]
I have some problem too @unional 
We need to disable `ter-indent`
