### ISSUE TITLE
Enable space-before-function-paren

### ISSUE THREAD

**Issue by victorandree** [blakeembrey/tslint-config-standard#17]
This rule is now available in tslint: https://palantir.github.io/tslint/rules/space-before-function-paren/

**Comment by blakeembrey** [comment]
Awesome, cheers! I'll enable this with `4.0`.

**Comment by blakeembrey** [comment]
Added with https://github.com/blakeembrey/tslint-config-standard/commit/59965f4a359343c428ce4fee7c2acc9784b662f2.
