### ISSUE TITLE
TSLint v5

### ISSUE THREAD

**Issue by mightyiam** [blakeembrey/tslint-config-standard#18]
[Has been released](https://github.com/palantir/tslint/releases/tag/5.0.0).

And I'm getting this:
`Warning: The 'no-use-before-declare' rule requires type checking`

There is something in the release notes about it.

**Comment by evollu** [comment]
you can get around by adding `--type-check` to tslint command

**Comment by blakeembrey** [comment]
@mightyiam I'm not really sure what this issue is for and what you'd like to see done here. Let me know if there's something you do need, otherwise I'm closing as you should use @evollu's suggestion. That's what the warning is about.

**Comment by mightyiam** [comment]
I think #22 fixed this. Thank you!

**Comment by fabiohbarbosa** [comment]
Example to fix warning message: `node_modules/.bin/tslint --type-check --project tslint.json src/**/**.ts`

**Comment by lohiarahul** [comment]
Adding --type-check to the tslint command didnt work for me

**Comment by blakeembrey** [comment]
@lohiarahul Why didn't it work? What error is you get? Did you set `--project`?

**Comment by lohiarahul** [comment]
Yes. "lint": "npm run tslint --type-check --project --force \"src/**/*.ts\"",

**Comment by lohiarahul** [comment]
Still shows 

> Warning: The 'no-use-before-declare' rule requires type infomation.

**Comment by blakeembrey** [comment]
Your NPM script is also wrong. You need to separate arguments with `--` if you expect arguments to be passed through. Currently your flags aren't used and are doing nothing. Read the NPM docs here: https://docs.npmjs.com/cli/run-script.

**Comment by fsenart** [comment]
Based on @blakeembrey comment, this works for me: `npm run lint -- --type-check`

**Comment by lohiarahul** [comment]
I see t

> Your NPM script is also wrong. You need to separate arguments with -- if you expect arguments to be passed through. Currently your flags aren't used and are doing nothing. Read the NPM docs here: https://docs.npmjs.com/cli/run-script.

i do have used -- in the script i pasted above

**Comment by lohiarahul** [comment]
> You need to actually point the --project to something, like #18 (comment) said. You can read the docs from TSLint: https://palantir.github.io/tslint/usage/cli/.

Is the project specified inline ? "lint": "npm run tslint --type-check --project:"../tsconfig.json" --force "src/**/*.ts"" The doc doesnt have an example

**Comment by blakeembrey** [comment]
@lohiarahul Again, you need two dashes after `npm run tslint` to pass arguments to the NPM script. You did not use ` -- ` in either script you pasted unless you've lost formatting. In which case, I'd recommend you use code blocks in markdown.

You also use an `=`, not `:`, to specify the argument. You also need backslashes to escape quotes in JSON.
