### ISSUE TITLE
Abstract class shouldn't error for empty methods

### ISSUE THREAD

**Issue by QuantumInformation** [blakeembrey/tslint-config-standard#19]
![image](https://cloud.githubusercontent.com/assets/216566/24516813/df60b8fe-1573-11e7-98ab-391f8127921c.png)

![image](https://cloud.githubusercontent.com/assets/216566/24516816/e39456f6-1573-11e7-9c83-568abe26e845.png)

**Comment by blakeembrey** [comment]
Sounds like an issue for the rules repo?

**Comment by QuantumInformation** [comment]
Which one is that?

**Comment by blakeembrey** [comment]
Probably https://palantir.github.io/tslint/rules/no-empty/ - you can use a comment for now. Not sure what the behaviour compared to ESLint is here.

**Comment by QuantumInformation** [comment]
Well I doubt there is one, since there is no abstract class. Would be trick to implement a layer on top just for TS too I think.

**Comment by blakeembrey** [comment]
I realise. You could compare the configuration that exists, there's likely a case for finer grain configuration in the rules. From what I can tell, ESLint separates it into block and function checks. Maybe it's something to propose into one of the rule repos? Unless you have a suggestion for this repo, I'll close it in favour of an issue in either ESLint rules or TSLint. Feel free to link it back here for context 😄

**Comment by blakeembrey** [comment]
I'd say make an issue in https://github.com/buzinas/tslint-eslint-rules to be more specific and similar to ESLint's built-in rules and make a second issue in TSLint itself - it seems like an oversight to not support abstract methods (via configuration or by default).

**Comment by blakeembrey** [comment]
Also, there weren't any line numbers so I couldn't really tell if something was minimised or not. You should consider using markdown code blocks to make it easier. But I think you may have been using the method incorrectly too - why not mark the method as abstract so it doesn't need a body at all?

**Comment by QuantumInformation** [comment]
Thanks, just using `  abstract draw (canvas: CanvasRenderingContext2D)`
fixes it for me!
