### ISSUE TITLE
Please upgrade tslint-eslint-rules dependency to v4.0.0

### ISSUE THREAD

**Issue by mdurling** [blakeembrey/tslint-config-standard#23]
[v4.0.0](https://github.com/buzinas/tslint-eslint-rules/releases/tag/v4.0.0)

Alternately, make tslint-eslint-rules a peer dependency so we can upgrade it independently.

Also, please allow tslint@5.0.0 as a peer dependency.

**Comment by blakeembrey** [comment]
See https://github.com/blakeembrey/tslint-config-standard/pull/22#issuecomment-291751137
