### ISSUE TITLE
Linting for js files

### ISSUE THREAD

**Issue by qqilihq** [blakeembrey/tslint-config-standard#42]
Great work, thank you. This is more a general question than an issue, still I would appreciate some input: 

We currently have a mixture of ts/js files in our project and I'd like to lint the js files with tslint as well.

When using the `tslint:recommended` rules, there are `jsRules`. `tslint-config-standard` and `tslint-eslint-rules` provide no `jsRules` however. 

Is there any package or setting which I could use to have the 'JS Standard Style' linting for js files with tslint?

**Comment by jrobeson** [comment]
@qqilihq : follow this tslint PR: https://github.com/palantir/tslint/pull/3641 . It sounds like you can set `jsRule: true` in `tslint.json` and it'll automatically apply any rules that aren't typescript specific.

**Comment by qqilihq** [comment]
Thanks for feedback! As chance will have it, we've now migrated all our JS files to TS, so I'm currently not able to give it a try, but I'll keep it in mind for future projects.
