### ISSUE TITLE
Consider adding tslint-sonarts rules

### ISSUE THREAD

**Issue by stas-vilchik** [blakeembrey/tslint-config-standard#43]
I'm a developer of [SonarTS](https://github.com/SonarSource/SonarTS) code analyzer, and we have the tslint extension which can be interesting for you. Most of the rules are built to detect bugs and different suspicious patters, they don't generate false positives, and therefore the extension is a good choice for any code base.

Could you give it a try and then consider adding it to your project if you like it? And if you don't, the feedback will be greatly appreciated :)

**Comment by blakeembrey** [comment]
I recall looking at it and didn't see any overlap with what we're trying to achieve here, which is StandardJS rules in TSLint. Let me know if you feel there is a usage I've overlooked!
