### ISSUE TITLE
Using tslint-config-standard produces several warnings

### ISSUE THREAD

**Issue by stephenmathieson** [blakeembrey/tslint-config-standard#48]
With this `tslint.json` file:

```json
{
  "extends": [
    "tslint-config-standard"
  ]
}
```

Running tslint emits several warnings:

```
$ npx tslint src/file.ts
Warning: The 'await-promise' rule requires type information.
Warning: The 'deprecation' rule requires type information.
Warning: The 'no-unused-variable' rule requires type information.
Warning: The 'no-use-before-declare' rule requires type information.
Warning: The 'no-floating-promises' rule requires type information.
Warning: The 'no-unnecessary-qualifier' rule requires type information.
Warning: The 'no-unnecessary-type-assertion' rule requires type information.
Warning: The 'strict-type-predicates' rule requires type information.
```

Note that `src/file.ts` contains no lint issues:

```
$ cat src/file.ts
console.log('Test')
```

Is there something I'm missing/doing wrong, or are these warnings expected?

**Comment by blakeembrey** [comment]
It’s in the README. Some rules require type information so you must use the project CLI flag. Feel free to read more on the TSLint site.

**Comment by blakeembrey** [comment]
I’ll link the option in the README to https://palantir.github.io/tslint/usage/cli/ in the future.

**Comment by stephenmathieson** [comment]
Wow, you're right, and I completely missed that. Strange that `tslint` doesn't find `tsconfig.json` on its own (like `tsc` does).

Sorry for the issue noise. Closing.
