### ISSUE TITLE
Remove no-unused-variable (deprecated in tslint)

### ISSUE THREAD

**Issue by damianb** [blakeembrey/tslint-config-standard#49]
Current versions of tslint emit the following deprecation warning:

    no-unused-variable is deprecated. Since TypeScript 2.9. Please use the built-in compiler checks instead.

**Comment by unional** [comment]
To workaround this for now, you can add the following to your tslint.json:

```json
{
  "rules": {
    "no-unused-variable": undefined
  }
}
```

**Comment by DaniGuardiola** [comment]
@unional thanks!!

**Comment by unional** [comment]
Yes, you can set it to `false`. I set it to null in my `tslint-config-unional` because I don't want to dictate the value to the end consumer, although the behavior is exactly the same. 🌷

**Comment by blakeembrey** [comment]
Feel free to submit a PR removing this!

**Comment by jrobeson** [comment]
Is there a way to make it conditional on typescript version? or does that not matter enough?

**Comment by blakeembrey** [comment]
Doesn't matter enough, just go for it 😄 It's unfortunate it was deprecated at all, even though TypeScript has the functionality built-in. I wonder if it's just to remove the additional overhead of maintenance?

**Comment by unional** [comment]
I did that in my package

**Comment by jrobeson** [comment]
I didn't understand why, but folks were talking about how it was either difficult or impossible to implement no-unused-variable in the language service
