### ISSUE TITLE
Warnings when linting

### ISSUE THREAD

**Issue by lepieru** [blakeembrey/tslint-config-standard#56]
I have some warnings when I lint my source files:

```
Warning: The 'await-promise' rule requires type information.
Warning: The 'deprecation' rule requires type information.
Warning: The 'no-floating-promises' rule requires type information.
Warning: The 'no-unnecessary-qualifier' rule requires type information.
Warning: The 'no-unnecessary-type-assertion' rule requires type information.
Warning: The 'strict-type-predicates' rule requires type information.
```

I does not append with `tslint:recommended`.

My environment:
- `node` version `10.15.0`
- `typescript` version `3.2.4`
- `tslint-config-standard` version `8.0.1`

**Comment by blakeembrey** [comment]
See https://github.com/blakeembrey/tslint-config-standard#usage

> Some TSLint rules require the use of --project to run.
